name: Build

on:
  push:
    branches: [ main ]
    paths:
      - '**'
      - '!docs/**' # ignore docs changes
      - '!**.md' # ignore markdown changes
  pull_request:
    branches: [ main ]
    paths:
      - '**.go'
      - 'go.*'
      - 'cmd/go.*'
      - 'Makefile'
      - 'Dockerfile'
      - 'integration/**'
      - 'scripts/**'

jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
      - uses: uraimo/run-on-arch-action@v2.5.1
        with:
          go-version: '1.20.6'
          arch: armv7
          distro: ubuntu20.04
      - run: make
      - run: make test
  integration:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        containerd: ["1.6.19", "1.7.0"]
    env:
      DOCKER_BUILD_ARGS: "CONTAINERD_VERSION=${{ matrix.containerd }}"
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
      - uses: uraimo/run-on-arch-action@v2.5.1
        with:
          go-version: '1.20.6'
          arch: armv7
          distro: ubuntu20.04
      - run: make integration
