name: Build

on:
  push:
    branches: ['main', 'release/**']
    paths:
      - '**'
      - '!docs/**' # ignore docs changes
      - '!**.md' # ignore markdown changes
  pull_request:
    branches: ['main', 'release/**']
    paths:
      - '.github/workflows/build.yml'
      - '**.go'
      - 'go.*'
      - 'cmd/go.*'
      - 'Makefile'
      - 'Dockerfile'
      - 'integration/**'
      - 'scripts/**'
      - '!benchmark/**'

env:
  GO_VERSION: '1.22.11'

jobs:
  setup:
    uses: awslabs/soci-snapshotter/.github/workflows/setup.yml
    outputs:
      available-runners: ${{ matrix.use-codebuild && toJSON(matrix.runs-on-names-cb) || toJSON(matrix.runs-on-names-gh) }}
      runner-labels: ${{ toJSON(matrix.runner-labels) }}
    steps:
      - name: Dump Config
        run: echo '${{ toJSON(matrix) }}'

  test:
    needs: setup
    runs-on: ${{ fromJSON(needs.setup.outputs.runner-labels)[matrix.os] }}
    strategy:
      matrix:
        os: ${{ fromJSON(needs.setup.outputs.available-runners) }}
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}
      - name: Install zlib static on AL2 ARM instances
        if: matrix.os == 'al2-arm'
        run: dnf install zlib-static.aarch64 -y
      - run: make
      - run: make test-with-coverage
      - name: Show test coverage
        run: make show-test-coverage

  integration:
    needs: setup
    runs-on: ${{ fromJSON(needs.setup.outputs.runner-labels)[matrix.os] }}
    timeout-minutes: 40
    strategy:
      fail-fast: false
      matrix:
        os: ${{ fromJSON(needs.setup.outputs.available-runners) }}
        containerd: ["1.6.36", "1.7.25", "2.0.2"]
    env:
      DOCKER_BUILD_ARGS: "CONTAINERD_VERSION=${{ matrix.containerd }}"
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}
      - name: Install zlib static on AL2 ARM instances
        if: matrix.os == 'al2-arm'
        run: dnf install zlib-static.aarch64 -y
      - run: make integration-with-coverage
      - name: Show test coverage
        run: make show-integration-coverage
