name: "Create THIRD_PARTY_LICENSES file"

on:
  create:
    branches: ['release/**']
  # We don't test on PR as all we are really doing is running the helper script
  # Run workflow on all pushes to a release branch
  push:
    branches: ['release/**']

permissions:
  contents: write
  pull-requests: write

jobs:
  initial-pr:
    runs-on: ubuntu-22.04
    env:
      MAJOR_MINOR: '' # Set in steps
      VERSION: '' # Set in steps

    permissions:
      # Write permissions needed to create pull request.
      # Risk for pwn requests is mitigated by seperating jobs such that
      # workflows running with write permissions only use code from the
      # branch which was cut from main.
      contents: write
      pull-requests: write

    steps:
      - name: Set env vars
        run: |
          branch_name=${{ github.ref_name }}
          major_minor=${branch_name#*/}
          echo "MAJOR_MINOR=${major_minor}" >> $GITHUB_ENV
          echo "VERSION=v${major_minor}.0" >> $GITHUB_ENV

      - uses: actions/checkout@v4
        with:
          ref: ${{ github.ref_name }}

      - uses: actions/setup-go@v5

      - name: Install go-licenses
        run: go install github.com/google/go-licenses@v1.6.0

      - name: Generate third party licenses file
        # This always fails due to issues with non-Go-modules + non-Go packages so never fail
        run: bash scripts/build-third-party-licenses.sh || true

      - name: Create PR
        uses: peter-evans/create-pull-request@v6
        with:
          title: 'Add third party licenses for ${{ env.VERSION }}'
          commit-message: |
            Add third party licenses for ${{ env.VERSION }}.
          body: |
            This change adds the THIRD_PARTY_LICENSES file for ${{ env.VERSION }}.

            This PR must be closed and reopened manually to trigger automated checks.

            Auto-generated by [create-pull-request](https://github.com/peter-evans/create-pull-request)
          labels: easy-to-review, automated-pr
          token: ${{ secrets.GITHUB_TOKEN }}
          author: "GitHub <no-reply@github.com>"
          signoff: true
          branch: 'create-pull-request/third-party-licenses-${{ env.VERSION }}'
          base: '${{ github.ref_name }}'
          delete-branch: true
