name: Update getting started guide

on:
  release:
    types: ['released']
  pull_request:
    branches: ['main']
    paths:
      # Run workflow on changes to the workflow definition itself to spot check
      # the core version update functionality.
      - '.github/workflows/update-getting-started-guide.yml'
      - 'scripts/update-getting-started-guide-version.sh'
      # Run workflow on changes to the getting started guide to validate
      # changes to the documentation do not break the update workflow.
      - 'docs/getting-started.md'
  # Run workflow on all pushes to a release branch
  push:
    branches: ['release/**']

jobs:
  test-update-version:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-22.04

    permissions:
      contents: read
      pull-requests: read

    steps:
      - uses: actions/checkout@v6
        with:
          sparse-checkout: |
            docs/eks.md
            docs/getting-started.md
            scripts/update-getting-started-guide-version.sh

      - name: Test update getting started version
        run: bash scripts/update-getting-started-guide-version.sh --assert v0.0.0-${{ github.event.pull_request.number }}

  update-version:
    if: github.event_name == 'release' || github.event_name == 'push'
    runs-on: ubuntu-22.04
    env:
      TAG_NAME: '' # Set in steps

    permissions:
      # Write permissions needed to create pull request.
      # Risk for pwn requests is mitigated by seperating jobs such that
      # workflows running with write permissions only use code from main.
      contents: write
      pull-requests: write

    steps:
      - name: "Set tag name for release"
        if: github.event_name == 'release'
        run: echo "RELEASE_TAG=${{ github.event.release.tag_name }}" >> $GITHUB_ENV
      - name: "Set tag name for push"
        if: github.event_name == 'push'
        run: |
          # curl GitHub API to get latest tag
          latest_tag=$(curl -s https://api.github.com/repos/awslabs/soci-snapshotter/releases| grep "tag_name" | cut -d '"' -f 4 | head -n 1)
          
          # Increment patch ver
          echo "RELEASE_TAG=$(echo ${latest_tag} | awk -F. -v OFS=. '{$NF += 1 ; print}')" >> $GITHUB_ENV
      - uses: actions/checkout@v6
        with:
          ref: main
          sparse-checkout: |
            docs/eks.md
            docs/getting-started.md
            scripts/update-getting-started-guide-version.sh

      - name: Update getting started version
        run: bash scripts/update-getting-started-guide-version.sh --verbose ${{ github.event.release.tag_name }}

      - name: Create PR
        uses: peter-evans/create-pull-request@v8
        with:
          title: 'Update getting started to ${{ github.event.release.tag_name }}'
          commit-message: 'Update getting started to ${{ github.event.release.tag_name }}'
          body: |
            This PR must be closed and reopened manually to trigger automated checks.

            Auto-generated by [create-pull-request](https://github.com/peter-evans/create-pull-request).
          labels: easy-to-review, automated-pr
          token: ${{ secrets.GITHUB_TOKEN }}
          author: "GitHub <no-reply@github.com>"
          signoff: true
          branch: 'create-pull-request/update-getting-started-version-to-${{ github.event.release.tag_name }}'
          base: main
          delete-branch: true
